// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

var localStorageKey = "wallet";

function getWalletValue(param) {
  var value = localStorage.getItem(localStorageKey);
  if (value !== null) {
    return Caml_format.caml_int_of_string(value);
  } else {
    return 0;
  }
}

function Wallet(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setWalletBalance = match[1];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setBalance = match$1[1];
  var balance = match$1[0];
  var onDepositClick = function (param) {
    var updatedWallet = String(getWalletValue(undefined) + Caml_format.caml_int_of_string(balance) | 0);
    localStorage.setItem(localStorageKey, updatedWallet);
    return Curry._1(setWalletBalance, (function (param) {
                  return updatedWallet;
                }));
  };
  var onWithdrawClick = function (param) {
    var updatedWallet = String(getWalletValue(undefined) - Caml_format.caml_int_of_string(balance) | 0);
    localStorage.setItem(localStorageKey, updatedWallet);
    return Curry._1(setWalletBalance, (function (param) {
                  return updatedWallet;
                }));
  };
  React.useEffect((function () {
          var currentWalletValue = getWalletValue(undefined);
          Curry._1(setWalletBalance, (function (param) {
                  return String(currentWalletValue);
                }));
          
        }), ([]));
  return React.createElement("div", undefined, React.createElement("h3", {
                  className: "balance"
                }, "Wallet balance: " + match[0]), React.createElement("br", undefined), React.createElement("input", {
                  className: "input-wallet",
                  type: "number",
                  value: balance,
                  onChange: (function ($$event) {
                      var value = $$event.target.value;
                      return Curry._1(setBalance, (function (param) {
                                    return value;
                                  }));
                    })
                }), React.createElement("button", {
                  className: "btn-deposit",
                  onClick: onDepositClick
                }, "Deposit"), React.createElement("button", {
                  className: "btn-withdraw",
                  onClick: onWithdrawClick
                }, "Withdraw"));
}

var make = Wallet;

export {
  localStorageKey ,
  getWalletValue ,
  make ,
  
}
/* react Not a pure module */
