// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Wallet$LootCheck from "../Wallet/Wallet.bs.js";

function App(Props) {
  return React.createElement(Wallet$LootCheck.make, { });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
